### PR TITLE
Invalidate serversToPlayersCache on player updates

### LINKED ISSUE #102: RedisBungeeAPI.getRedisBungeeApi().getPlayersOnServer() returning empty set
### intended behavior

`RedisBungeeAPI.getRedisBungeeApi().getPlayersOnServer("test")` should return a set containing my UUID.

### what the behavior you actually saw

It instead returns an empty set.

### Steps to reproduce

Under a proxy, connect to a server (lobby) then switch to a server (test). Then run `RedisBungeeAPI.getRedisBungeeApi().getPlayersOnServer("test")`, which should return an empty set.

### Velocity or Bungeecord Versions

Velocity 3.3.0

### RedisBungee Version & Redis Version

Redis Cluster 7.2.4
RedisBungee 0.12.3

### Other

This is a dump of the player data as the bug was observed. Also note that last-server is equal to server, is this intentional?

```
127.0.0.1:6379> hgetall redis-bungee::main::player::(my-uuid)::data
 1) "last-online"
 2) "0"
 3) "last-server"
 4) "test"
 5) "proxy"
 6) "main-proxy"
 7) "ip"
 8) "127.0.0.1"
 9) "server"
10) "test"
```

### PR DESCRIPTION
**Pull request by md5nake**
This closes #102

### CODE REVIEW

**Comment by md5nake** [comment]
I think this is a better approach than removing caching entirely. The less we query Redis, the better

**Comment by ham1255** [comment]
thing is even if this cache existed like what i saw in the code, that players frequently change servers which makes cache useless due huge amounts of invalidated stuff

**Comment by md5nake** [comment]
Even if cache invalidations are frequent, we still invalidate it when an update is made, and in the meantime we might get some cache hits.

**Comment by ham1255** [comment]
looks good then, i reverted my commit

**Pull request merged**
